version: "3.9"

services:
  # Auth db (spring auth db)
  db_auth:
    image: postgres:15
    container_name: wrenchit-postgres-auth
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_AUTH_USER} -d ${POSTGRES_AUTH_DB}"]
      interval: 5s
      timeout: 3s
      retries: 15

  # App db
  db_app:
    image: postgres:15
    container_name: wrenchit-postgres-app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_APP_USER}
      POSTGRES_PASSWORD: ${POSTGRES_APP_PASSWORD}
      POSTGRES_DB: ${POSTGRES_APP_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_APP_USER} -d ${POSTGRES_APP_DB}"]
      interval: 5s
      timeout: 3s
      retries: 15

  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: wrenchit-clamav
    ports:
      - "${CLAMAV_PORT:-3310}:3310"
    restart: unless-stopped

volumes:
  postgres_auth_data:
  postgres_app_data:
